name: AWS CDK Synth

on:
  push:
    branches:
      - main

env:
  REGION: 'us-west-2'

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}
          role-to-assume: ${{ secrets.GH_ROLE_ARNAA }}
          role-duration-seconds: 1200yy
          role-session-name: GitActionDeploymentSession
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      - name: Prerequisite Installation
        run: |
          cd $GITHUB_WORKSPACE
          npm --version
          npm install
          npx cdk --version
      - name: Build & Deploy
        env:
          CFN_ROLE: ${{secrets.CFN_EXECUTION_ROLE}}
        run: |
          cd $GITHUB_WORKSPACE
          chmod 700 build.sh
          ./build.sh
          npx cdk synth
          npx cdk —require-approval never -r $CFN_ROLE
